### ISSUE TITLE
different results from running directly make and grid_generate.py

### ISSUE THREAD

**Issue by anzalks** [anzalks/Pattern_generation#2]
I tried to run the script from terminal using:
1)make 
with  -N 100 -H 29 -W 29 --num-brights 5 --num-fixed-brights 1 \
	    --gap 1 \ editted into itinstead of running grid_generate.py from terminal
This gave me the desired output. 
![results tiff](https://user-images.githubusercontent.com/44459736/67874312-c14a2100-fb5a-11e9-8968-7a2a124cf7e6.png)

2) I tried running the script grid_generate.py from terminal by
./grid_generator.py -W 29 -H 29 -nB 5 -g 1 -N 100 -o 29_29_5lit_1_gap_100_samples.tiff
and got an undesired result. 
the % coverage is too low and the spacing criteria between the grids are nto followed properly(tested with a larger sampling rate and got points overlaping )

![29_29_5lit_1_gap_100_samples tiff](https://user-images.githubusercontent.com/44459736/67874409-e6d72a80-fb5a-11e9-92e6-c54f23efc831.png)

**Comment by dilawar** [comment]
Also do a `git pull`, I have tweaked the histogram a bit. See if undesired goes away.
