### ISSUE TITLE
Need help in eliminating some rows at the top and the bottom. 

### ISSUE THREAD

**Issue by anzalks** [anzalks/Pattern_generation#6]
![cropped ROI](https://user-images.githubusercontent.com/44459736/73921009-8b9c9d00-48ec-11ea-8165-9718ba4bb72b.png)
I would like to get the red shaded area to be ignored while generating images with bright points. 
The array dimension shouldn't change. But the images with bright pixels in those row values(it can be an arbitrary value ) shouldn't be saved at the end(say we had 625 images, now we will have "x" number of upper and lower rows less as out file). The number of rows and the bottom can be variable but they can be kept constant for a single run.

**Comment by dilawar** [comment]
If there is any pixel in the red top and bottom areas (height 5px, 5 rows), discard the image.
